# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mastodon}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Colin Shea"]
  s.date = %q{2009-12-23}
  s.description = %q{Mastodon: A ruby parser for todo.txt files.

And the mastodon, like plain text, isn't extinct! (Yet.)}
  s.email = %q{colin@evaryont.me}
  s.extra_rdoc_files = [
    "README.mkd"
  ]
  s.files = [
    "Rakefile",
     "VERSION.yml",
     "lib/mastodon.rb",
     "lib/mastodon/todo.rb",
     "lib/mastodon/version.rb",
     "test/run_tests.rb",
     "test/test_helper.rb",
     "test/test_mastodon.rb",
     "test/todo.txt"
  ]
  s.homepage = %q{http://github.com/evaryont/mastodon/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A ruby parser for todo.txt files}
  s.test_files = [
    "test/run_tests.rb",
     "test/test_helper.rb",
     "test/test_mastodon.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

